# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
    # Pods for PollPit
    pod 'Alamofire'
    pod 'Kingfisher' #https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet
    pod 'NVActivityIndicatorView' #https://github.com/ninjaprox/NVActivityIndicatorView
    pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip', :branch => 'master'
    pod 'RSSelectionMenu' or pod 'RSSelectionMenu', '~> 5.3.2'
    pod 'SwiftVideoBackground', '~> 3.0'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Google-Mobile-Ads-SDK'
    pod 'MerchantKit'
    pod 'Firebase/Core'
    pod 'FacebookCore'

end


target 'NYCFireWire - Prod' do
  use_frameworks!
  shared_pods
end

target 'NYCFireWire - Local' do
  use_frameworks!
  shared_pods
end

target 'NYCFireWire - Staging' do
  use_frameworks!
  shared_pods
end
